# Generated by Django 5.0.7 on 2024-07-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
